# .github/workflows/main.yml
name: CI/CD Pipeline for Elearning Platform

on:
  push:
    branches:
      - main # O la rama principal que uses
  pull_request:
    branches:
      - main

jobs:
  quality-and-security-checks:
    name: Quality and Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # Detener el build si hay errores de Python, pero permitir advertencias.
          # --count muestra el número total de errores.
          # --show-source muestra el código problemático.
          # --statistics muestra un conteo de cada error/advertencia.
          flake8 logica_recursos/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Security scan with Bandit
        run: |
          bandit -r logica_recursos/

      - name: Run unit tests with pytest
        run: |
          pytest --cov=logica_recursos --cov-report=xml

      - name: Infrastructure security scan with tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .
